# Generated by Django 4.0.4 on 2022-06-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_product_prod_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(default='', upload_to='prod_img'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_price',
            field=models.IntegerField(default=0),
        ),
    ]
