# Generated by Django 4.0.4 on 2022-06-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_rename_prod_img_product_prod_img_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_img_fold',
            field=models.ImageField(default='', upload_to='prod_img'),
        ),
    ]
