# Generated by Django 4.0.4 on 2022-06-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_product_prod_img_fold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_img_fold',
            field=models.ImageField(default='', null=True, upload_to='prod_img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img_side',
            field=models.ImageField(default='', null=True, upload_to='prod_img'),
        ),
    ]
