# Generated by Django 4.0.4 on 2022-06-26 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0008_rename_prod_img_fold_product_prod_img_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
