# Generated by Django 4.0.4 on 2022-06-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_alter_product_prod_img_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_img_main',
            field=models.ImageField(blank=True, null=True, upload_to='prod_img'),
        ),
    ]
