# Generated by Django 4.0.4 on 2022-06-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
